version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - uploads:/app/uploads
  db:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  uploads:
  postgres:
